### ISSUE TITLE
Assignment 43 - in class

### ISSUE THREAD

**Issue by brianburridge** [Billboz/Assignments#49]
## Assignment 43 - in class
- Create a custom rake task, in the app used on assignment 42, that will output the current count of all your models (these can be hardcoded)
  Ex:

```
    Teams: 4
    Users: 10
    Books: 15
    Authors: 2
    Movies: 1
```

**Comment by Billboz** [comment]
Here is the https://github.com/Billboz/Apprentice_to_Master
